server:
  port: 8111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springdb
#    username: root
#    password: '0000'
    url: jdbc:mysql://project1.cxg8vdlfu0la.ap-southeast-2.rds.amazonaws.com:3306/dev
    username: admin
    password: '00000000'

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # DDL?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  # yaml/yml ?? - Thymeleaf ??
  thymeleaf:
    cache: false
    check-template-location: true
    #    prefix: classpath:/templates/
    #    suffix: .html
    enabled: true

#    #live reload 설정 배포시 주석
#    prefix: file:src/main/resources/templates/
#
#    #live reload 설정 배포시 주석
#    devtools:
#      livereload:
#        enabled: true
#      thymeleaf:
#        cache: false
#      restart:
#        enabled: true



  #application-oauth2
  profiles:
    include: oauth2

  # code.aiaru@gmail.com
  servlet:
    multipart:
      # 단일 파일에 대한 최대 허용 크기.
      max-file-size: 10MB
      # 전체 HTTP 요청에 대한 최대 허용 크기.
      max-request-size: 50MB

# code.aiaru@gmail.com
file:
  productImgUploadDir: C:\Users\code.aiaru\Desktop\coding\saveFiles\productImg\ # 상품이미지 경로 (절대경로로 설정해주세요)
  reviewImgUploadDir: C:\Users\code.aiaru\Desktop\coding\saveFiles\reviewImg\   # 리뷰이미지 경로 (절대경로로 설정해주세요)
  mainSliderImgDir: \images\mainSilderImg\